package com.buyash.entity;

public enum Instrument {
    ACCORDION, PIANO, GUITAR, ORCHESTRA, VIOLIN, DRUMS, CELLO,
    SAXOPHONE, TRUMPET, PIPES, TRIANGLES, DJ_MIXER,
    SET_OF_INSTRUMENTS, NOT_AN_INSTRUMENT, NO_INSTRUMENT
}
